### PR TITLE
feat: copy dotnet examples from examples repo

### PR DESCRIPTION
**Pull request by cprice404**
We are in the process of moving the examples out of the old examples repo and into the individual SDK repos.  This commit copies the dotnet examples over; no changes.

Also copies over Pete's dependabot/examples CI work.

### CODE REVIEW

**Review by eaddingtonwhite — APPROVED** [review]
Thank you for the copy pasta 🙇 🍝

**Review by pgautier404 — APPROVED** [review]

**Review by malandis — COMMENTED** [review]
Is dependabot still necessary now that the examples are in this repo and part of the CI workflow?

**Comment by cprice404** [comment]
> Is dependabot still necessary now that the examples are in this repo and part of the CI workflow?

yes, it enforces that the examples get tested with the latest binary release of the SDK when the SDK is released.

**Comment by malandis** [comment]
Got it -- the release artifact vs in repo build difference!

**Review by malandis — APPROVED** [review]

**Pull request merged**
